jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  workspace:
    clean: all
  variables:
  - name: BuildConfiguration
    value: release
  - group: BUILD Management Resources
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-employercommitments-v2

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'